"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Heart } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useStore } from "./provider";
import { api, errorMessage } from "@/lib/client";
import type { User } from "@/lib/types";
export function AuthForm({ register = false, next = "/profile" }: { register?: boolean; next?: string }) {
  const { t, setUser, refreshCart } = useStore();
  const router = useRouter();
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState("");
  const destination = next.startsWith("/")&&!next.startsWith("//")&&!next.includes("\\") ? next : "/profile";
  return <section className="page-container grid max-w-5xl gap-12 py-16 md:grid-cols-2 md:items-center"><div className="hidden rounded-2xl bg-secondary p-12 md:block"><Heart className="mb-8 size-12 stroke-1 text-primary" /><p className="eyebrow mb-4 text-primary">{t("YOUR OWN LITTLE BEAUTY SPACE", "مساحتك الصغيرة للجمال")}</p><h1 className="heading text-primary">{t(register?"Let's make it official.":"Hello again, beautiful.",register?"خلينا نتعرف عليكِ.":"أهلاً برجعتك يا حلوة.")}</h1><p className="mt-6 text-sm leading-8 text-muted-foreground">{t("Save your details and keep your orders in one lovely place. Or simply shop as a guest — we're happy you're here.", "احفظي بياناتك وطلباتك بمكان واحد. أو تسوقي بدون حساب — مبسوطين بوجودك.")}</p></div><div className="soft-panel"><h2 className="mb-2 text-2xl font-semibold">{t(register?"Create an account":"Welcome back",register?"إنشاء حساب":"تسجيل الدخول")}</h2><p className="mb-7 text-sm text-muted-foreground">{t(register?"A few details, and you're one of us.":"Your beauty favorites missed you.",register?"شوية تفاصيل وبتصيري من عيلتنا.":"مفضلاتك اشتاقتلك.")}</p><form className="space-y-5" onSubmit={async e => { e.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(e.currentTarget)); if (register && data.password!==data.confirmPassword) { setError(t("Passwords do not match.", "كلمتا المرور غير متطابقتين.")); return; } setBusy(true); try { const result = await api<{user:User}>(register?"auth/register":"auth/login","POST",data); setUser(result.user); await refreshCart(); router.push(destination); router.refresh(); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }}>
    {register && <><div className="field"><Label htmlFor="auth-name">{t("Full name", "الاسم الكامل")}</Label><Input id="auth-name" name="name" autoComplete="name" required maxLength={100} /></div><div className="field"><Label htmlFor="auth-phone">{t("Phone (optional)", "الهاتف (اختياري)")}</Label><Input id="auth-phone" name="phone" autoComplete="tel" type="tel" maxLength={30} /></div></>}
    <div className="field"><Label htmlFor="auth-email">{t("Email address", "البريد الإلكتروني")}</Label><Input id="auth-email" name="email" autoComplete="email" type="email" required maxLength={254} /></div><div className="field"><Label htmlFor="auth-password">{t("Password", "كلمة المرور")}</Label><Input id="auth-password" name="password" autoComplete={register?"new-password":"current-password"} type="password" required minLength={8} maxLength={128} />{register && <p className="text-xs text-muted-foreground">{t("At least 8 characters.", "8 أحرف على الأقل.")}</p>}</div>{register && <div className="field"><Label htmlFor="auth-confirm">{t("Confirm password", "تأكيد كلمة المرور")}</Label><Input id="auth-confirm" name="confirmPassword" autoComplete="new-password" type="password" required minLength={8} maxLength={128} /></div>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="h-11 w-full rounded-full" type="submit" disabled={busy}>{busy?t("Please wait…","لحظة من فضلك…"):t(register?"Create account":"Sign in",register?"إنشاء الحساب":"تسجيل الدخول")}</Button></form><p className="mt-6 text-center text-xs leading-7 text-muted-foreground">{t(register?"Already one of us?":"New here?",register?"عندك حساب؟":"جديدة هون؟")} <Link className="font-semibold text-primary underline underline-offset-4" href={`${register?"/login":"/register"}?next=${encodeURIComponent(destination)}`}>{t(register?"Sign in":"Would you like to create an account?",register?"تسجيل الدخول":"هل تريد إنشاء الحساب؟")}</Link></p><Button asChild variant="ghost" className="mt-3 w-full"><Link href={destination==="/checkout"?"/checkout":"/all-products"}>{t("Continue without an account", "المتابعة بدون حساب")}</Link></Button></div></section>;
}
