"use client";
import Link from "next/link";
import { useState } from "react";
import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { useStore } from "./provider";
import { ProductImage } from "./product-image";
import { errorMessage } from "@/lib/client";
export function EmptyBag() { const { t } = useStore(); return <div className="page-container py-24 text-center"><ShoppingBag className="mx-auto mb-6 size-12 text-accent" /><h1 className="heading">{t("A little room for something lovely", "في مكان لشي حلو بسلتك")}</h1><p className="mb-8 mt-4 text-sm text-muted-foreground">{t("Your bag is empty. Let's find your next favorite.", "سلتك فاضية. خلينا نلاقي منتجك المفضل الجديد.")}</p><Button asChild className="rounded-full"><Link href="/all-products">{t("Explore the shop", "تصفحي المتجر")}</Link></Button></div>; }
export function StoreLoading() { const { t, loadingError } = useStore(); return <div className="page-container py-20" role="status">{loadingError ? <div className="soft-panel"><p>{t("We couldn't load your bag. Please refresh to try again.", "تعذر تحميل السلة. أعيدي تحميل الصفحة للمحاولة.")}</p><Button className="mt-4" onClick={() => window.location.reload()}>{t("Try again", "حاولي مرة ثانية")}</Button></div> : <><span className="sr-only">{t("Loading", "جاري التحميل")}</span><Skeleton className="mb-8 h-12 w-60" /><Skeleton className="h-70 w-full" /></>}</div>; }
export function OrderSummary({ checkout = false }: { checkout?: boolean }) {
  const { t, currency, cart, applyVoucher, settings } = useStore();
  const [code,setCode] = useState("");
  const [busy,setBusy] = useState(false);
  const apply = async (value: string) => { setBusy(true); try { await applyVoucher(value); toast.success(t(value ? "Voucher applied" : "Voucher removed", value ? "تم تطبيق القسيمة" : "تم إزالة القسيمة")); } catch(e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  return <aside className="soft-panel h-fit lg:sticky lg:top-44"><h2 className="mb-6 text-lg font-semibold">{t("Order summary", "ملخص الطلب")}</h2>{checkout && <div className="mb-6 space-y-4 border-b pb-6">{cart.items.map(item => <div key={item.productId} className="flex justify-between gap-4 text-xs"><span>{t(item.product.name,item.product.nameAr)} × {item.quantity}</span><span className="shrink-0">{currency(item.product.price*item.quantity)}</span></div>)}</div>}<dl className="space-y-4 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">{t("Subtotal", "المجموع الفرعي")}</dt><dd>{currency(cart.subtotal)}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">{t("Delivery", "التوصيل")}</dt><dd>{cart.shipping ? currency(cart.shipping) : t("Free", "مجاني")}</dd></div>{cart.discount>0 && <div className="flex justify-between text-primary"><dt>{t("Discount", "الخصم")}</dt><dd>−{currency(cart.discount)}</dd></div>}<div className="flex justify-between border-t pt-4 text-lg font-semibold"><dt>{t("Total", "الإجمالي")}</dt><dd className="text-primary">{currency(cart.total)}</dd></div></dl><div className="my-6 rounded-lg bg-secondary/65 p-3 text-center text-xs leading-6 text-primary">{cart.subtotal>=settings.freeShippingThreshold ? t("A little extra love: your delivery is free.", "شوية حب زيادة: توصيلك مجاني.") : t(`You're ${currency(settings.freeShippingThreshold-cart.subtotal)} away from free delivery.`,`باقي ${currency(settings.freeShippingThreshold-cart.subtotal)} للتوصيل المجاني.`)}</div><form className="flex gap-2" onSubmit={e => { e.preventDefault(); apply(code); }}><Input aria-label={t("Voucher code", "رمز القسيمة")} placeholder={t("Voucher code", "رمز القسيمة")} value={code} onChange={e => setCode(e.target.value)} /><Button variant="outline" disabled={busy||!code.trim()} type="submit">{t("Apply", "تطبيق")}</Button></form>{cart.voucherCode && <div className="mt-3 flex items-center justify-between text-xs"><span>{cart.voucherCode}</span><button className="text-primary underline" disabled={busy} onClick={() => apply("")}>{t("Remove", "إزالة")}</button></div>}{!checkout && <Button asChild className="mt-6 h-12 w-full rounded-full"><Link href="/checkout">{t("Checkout", "إتمام الطلب")}</Link></Button>}<p className="mt-4 text-center text-[11px] text-muted-foreground">{t("Pay in cash when your order arrives.", "ادفعي نقداً عند استلام طلبك.")}</p></aside>;
}
export function CartPage() {
  const { t, currency, cart, updateCart, ready, loadingError } = useStore();
  const [busy,setBusy] = useState(false);
  const update = async (id: string, quantity: number) => { setBusy(true); try { await updateCart(id,quantity); } catch(e) { toast.error(errorMessage(e)); } finally { setBusy(false); } };
  if (!ready||loadingError) return <StoreLoading />;
  if (!cart.items.length) return <EmptyBag />;
  return <div className="page-container section-space"><p className="eyebrow mb-4 text-primary">{t("YOUR LITTLE BEAUTY HAUL", "اختياراتك الحلوة")}</p><h1 className="heading mb-3">{t("Your shopping bag", "سلة التسوق")}</h1><p className="mb-10 text-sm text-muted-foreground">{cart.items.reduce((s,i)=>s+i.quantity,0)} {t("lovely things, picked by you.", "منتجات حلوة، من اختيارك.")}</p>{cart.warning && <p role="status" className="mb-5 rounded-lg bg-secondary p-4 text-sm">{t(cart.warning, "تم تحديث السلة بسبب تغيير المخزون أو صلاحية القسيمة. يرجى مراجعة الكميات والإجمالي.")}</p>}<div className="grid items-start gap-10 lg:grid-cols-[1.7fr_1fr]"><div><div className="divide-y border-y">{cart.items.map(item => <div key={item.productId} className="flex gap-4 py-6"><Link href={`/product/${item.productId}`} className="relative h-32 w-25 shrink-0 overflow-hidden rounded-lg"><ProductImage src={item.product.images[0]} alt={t(item.product.name,item.product.nameAr)} sizes="100px" /></Link><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><Link href={`/product/${item.productId}`} className="text-sm font-semibold leading-6">{t(item.product.name,item.product.nameAr)}</Link><Button variant="ghost" size="icon" className="size-7 shrink-0 text-muted-foreground" aria-label={t("Remove item", "إزالة المنتج")} disabled={busy} onClick={() => update(item.productId,0)}><Trash2 className="size-4" /></Button></div><p className="mt-2 text-sm text-primary">{currency(item.product.price)}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center rounded-full border"><Button size="icon" variant="ghost" className="size-8 rounded-full" disabled={busy||item.quantity<=1} aria-label={t("Decrease quantity", "تقليل الكمية")} onClick={() => update(item.productId,item.quantity-1)}><Minus className="size-3" /></Button><span className="w-7 text-center text-xs">{item.quantity}</span><Button size="icon" variant="ghost" className="size-8 rounded-full" disabled={busy||item.quantity>=Math.min(item.product.stock,99)} aria-label={t("Increase quantity", "زيادة الكمية")} onClick={() => update(item.productId,item.quantity+1)}><Plus className="size-3" /></Button></div><span className="text-sm font-semibold">{currency(item.product.price*item.quantity)}</span></div></div></div>)}</div><Link href="/all-products" className="mt-6 inline-block text-sm text-primary underline underline-offset-4">{t("Continue exploring", "كمّلي تسوقك")}</Link></div><OrderSummary /></div></div>;
}
