"use client";
import Link from "next/link";
import { useState } from "react";
import { Check, CheckCircle2, UserRound, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useStore } from "./provider";
import { EmptyBag, OrderSummary, StoreLoading } from "./cart";
import { api, errorMessage } from "@/lib/client";
import type { Order } from "@/lib/types";
export function CheckoutPage() {
  const { t, cart, user, ready, loadingError, refreshCart, currency } = useStore();
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState("");
  const [order,setOrder] = useState<Order | null>(null);
  const [requestKey] = useState(() => typeof crypto !== "undefined" ? crypto.randomUUID() : "");
  if (order) return <div className="page-container max-w-2xl py-20 text-center"><CheckCircle2 className="mx-auto mb-6 size-16 text-primary" /><p className="eyebrow mb-4 text-primary">{t("A LITTLE BEAUTY IS ON ITS WAY", "طلبك الحلو وصلنا")}</p><h1 className="heading">{t("Thank you, beautiful.", "شكراً يا حلوة.")}</h1><p className="mt-5 text-sm leading-7 text-muted-foreground">{t("Your order is confirmed in our system. Save your order number for reference.", "تم تسجيل طلبك بنجاح. احتفظي برقم الطلب للرجوع إليه.")}</p><div className="soft-panel my-8 space-y-4"><p className="font-mono text-xl text-primary" dir="ltr">{order.id}</p><p>{currency(order.total)} · {t("Cash on delivery", "الدفع عند الاستلام")}</p><p className="text-sm text-muted-foreground">{order.city} · {order.address}</p></div><div className="flex flex-wrap justify-center gap-3"><Button asChild><Link href="/all-products">{t("Continue shopping", "متابعة التسوق")}</Link></Button>{!user ? <Button asChild variant="outline"><Link href="/register">{t("Would you like to create an account?", "هل تريد إنشاء الحساب؟")}</Link></Button> : <Button asChild variant="outline"><Link href="/profile">{t("View my orders", "عرض طلباتي")}</Link></Button>}</div></div>;
  if (!ready||loadingError) return <StoreLoading />;
  if (!cart.items.length) return <EmptyBag />;
  return <section className="page-container section-space"><p className="eyebrow mb-4 text-primary">{t("ONE LAST LITTLE STEP", "آخر خطوة صغيرة")}</p><h1 className="heading mb-10">{t("Make it yours", "إتمام الطلب")}</h1><div className="grid items-start gap-10 lg:grid-cols-[1.6fr_1fr]"><div>{!user && <div className="mb-7 flex flex-wrap items-center justify-between gap-4 rounded-xl bg-secondary p-5"><div className="flex items-center gap-3"><UserRound className="size-5 text-primary" /><div><p className="text-sm font-medium">{t("You're checking out as a guest", "عم تتممي الطلب بدون حساب")}</p><p className="mt-1 text-xs text-muted-foreground">{t("No account needed. You're always welcome.", "ما بتحتاجي حساب. أهلاً فيكِ دائماً.")}</p></div></div><div className="flex flex-wrap gap-2"><Button size="sm" asChild variant="outline"><Link href="/register?next=/checkout">{t("Would you like to create an account?", "هل تريد إنشاء الحساب؟")}</Link></Button><Button size="sm" variant="ghost" asChild><Link href="/login?next=/checkout">{t("Sign in", "تسجيل الدخول")}</Link></Button></div></div>}
  <form className="soft-panel" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(e.currentTarget)); try { const result = await api<{ order: Order }>("orders","POST",{ ...data,requestKey }); setOrder(result.order); await refreshCart(); window.scrollTo({top:0,behavior:"smooth"}); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><h2 className="mb-6 text-lg font-semibold">{t("Delivery details", "تفاصيل التوصيل")}</h2><div className="grid gap-5 sm:grid-cols-2">{[["name","Full name","الاسم الكامل","text",user?.name,"name"],["email","Email address","البريد الإلكتروني","email",user?.email,"email"],["phone","Phone number","رقم الهاتف","tel",user?.phone,"tel"],["city","City","المدينة","text",user?.city,"address-level2"]].map(([name,en,ar,type,value,auto]) => <div className="field" key={name}><Label htmlFor={`checkout-${name}`}>{t(en!,ar!)} *</Label><Input id={`checkout-${name}`} name={name} type={type} autoComplete={auto} defaultValue={value||""} required maxLength={name==="email"?254:100} /></div>)}<div className="field sm:col-span-2"><Label htmlFor="checkout-address">{t("Street address", "العنوان بالتفصيل")} *</Label><Input id="checkout-address" name="address" autoComplete="street-address" defaultValue={user?.address||""} placeholder={t("Street, building, and nearest landmark", "الشارع، المبنى، وأقرب معلم")} required maxLength={500} /></div><div className="field sm:col-span-2"><Label htmlFor="checkout-notes">{t("Delivery notes (optional)", "ملاحظات التوصيل (اختياري)")}</Label><Textarea id="checkout-notes" name="notes" maxLength={1000} placeholder={t("Anything we should know?", "في شي بتحبي تخبرينا فيه؟")} /></div></div><h2 className="mb-4 mt-8 text-lg font-semibold">{t("Payment", "الدفع")}</h2><div className="flex items-center justify-between rounded-lg border border-primary/30 bg-secondary/40 p-4"><div className="flex items-center gap-3"><Wallet className="size-5 text-primary" /><div><p className="text-sm font-medium">{t("Cash on delivery", "الدفع عند الاستلام")}</p><p className="mt-1 text-xs text-muted-foreground">{t("Pay when your lovely things arrive.", "ادفعي لما يوصل طلبك الحلو.")}</p></div></div><Check className="size-4 text-primary" /></div>{error && <p role="alert" className="mt-5 text-sm text-destructive">{error}</p>}<Button type="submit" className="mt-7 h-12 w-full rounded-full" disabled={busy}>{t(busy?"Placing your order…":"Place order",busy?"جاري تسجيل طلبك…":"تأكيد الطلب")} · {currency(cart.total)}</Button><p className="mt-3 text-center text-xs leading-6 text-muted-foreground">{t("Your details will be used to prepare and deliver your order.", "سنستخدم بياناتك لتجهيز طلبك وتوصيله.")}</p></form></div><OrderSummary checkout /></div></section>;
}
