import { loadEnvConfig } from '@next/env';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import mongoose from 'mongoose';
import { connectMongo } from '../src/lib/mongoose';
import { ProductModel, SyncStateModel } from '../src/lib/models';
import { syncHsabate } from '../src/lib/hsabate';
import { db, get, put, products, transaction } from '../src/lib/db';
import type { Product } from '../src/lib/types';
loadEnvConfig(process.cwd());
const uri = new URL(process.env.MONGODB_URI!);
const testDb = `oopsskin_sync_test_${randomUUID().replaceAll('-', '').slice(0, 12)}`;
uri.pathname = `/${testDb}`;
process.env.MONGODB_URI = uri.toString();
process.env.HSABATE_EMAIL = 'test@example.com';
process.env.HSABATE_PASSWORD = 'test-only';
const originalFetch = globalThis.fetch;
let rows = [{ id: '42', name: 'Test', price: '50', amount: 10, class_id: '3', cost: '12', item_img: null, measure: [1] }];
let visible = rows;
let invalid = false;
globalThis.fetch = async (_url, options) => {
  const form = options?.body as FormData;
  if (form.get('action') === 'Auth') return Response.json({ token: 'test-token' });
  if (invalid) return Response.json({ status: 'Error', code: '103', msg: 'should not leak supplier response' });
  if (form.get('type') === 'category') return Response.json({ status: 'succes', table: [{ id: '3', name: 'SKIN CARE' }] });
  return Response.json({ status: 'succes', table: form.get('all') === '0' ? visible : rows });
};
test('sync commits exact supplier records, is repeatable, retains reservations, archives and handles failure', async () => {
  await db();
  const first = await syncHsabate();
  assert.equal(first.inserted, 1);
  assert.ok(first.archived > 0);
  const raw = await ProductModel.collection.findOne({ externalId: '42' });
  for (const [key, value] of Object.entries(rows[0])) assert.deepEqual(raw?.[key], value);
  const product = (await get<Product>('products', 'hsabate:42'))!;
  assert.equal(product.id, 'hsabate:42');
  assert.equal(product.price, 50);
  assert.equal('cost' in product, false);
  await assert.rejects(() => transaction(async () => { await put('products', product.id, { ...product, stock: 5 }); throw new Error('rollback-test'); }), /rollback-test/);
  assert.equal((await get<Product>('products', product.id))?.stock, 10);
  await put('products', product.id, { ...product, stock: 8 });
  rows = [{ ...rows[0], name: 'Changed in API', price: '60', amount: 9 }]; visible = rows;
  const second = await syncHsabate();
  assert.equal(second.inserted, 0);
  assert.equal(second.updated, 1);
  assert.equal(await ProductModel.countDocuments({ externalSource: 'hsabate' }), 1);
  const changed = (await get<Product>('products', product.id))!;
  assert.equal(changed.name, 'Changed in API');
  assert.equal(changed.price, 60);
  assert.equal(changed.stock, 7);
  assert.equal((await ProductModel.collection.findOne({ externalId: '42' }))?.amount, 9);
  const before = await ProductModel.collection.find({}).toArray();
  invalid = true;
  await assert.rejects(syncHsabate, /code 103/);
  assert.deepEqual(await ProductModel.collection.find({}).toArray(), before);
  invalid = false;
  await SyncStateModel.updateOne({ _id: 'hsabate' }, { $set: { lockedUntil: new Date(Date.now() + 60000) } });
  await assert.rejects(syncHsabate, /already running/);
  await SyncStateModel.updateOne({ _id: 'hsabate' }, { $set: { lockedUntil: new Date(0) } });
  rows = [{ ...rows[0], id: '43' }]; visible = rows;
  const third = await syncHsabate();
  assert.equal(third.archived, 1);
  assert.equal((await get<Product>('products', product.id))?.active, false);
  assert.deepEqual((await products()).map(p => p.id), ['hsabate:43']);
});
test.after(async () => {
  globalThis.fetch = originalFetch;
  const mongo = await connectMongo();
  assert.equal(mongo.connection.name, testDb);
  try { for (const collection of await mongo.connection.db!.collections()) await collection.deleteMany({}); } finally { await mongoose.disconnect(); }
});
