"use client";
import { HsabateDashboard } from "./hsabate-dashboard";
import { useState } from "react";
import Link from "next/link";
import { ClipboardList, LayoutDashboard, Package, Plus, Settings, TicketPercent, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useStore } from "@/components/store/provider";
import { Status } from "@/components/store/profile";
import { api, errorMessage } from "@/lib/client";
import { cn } from "@/lib/utils";
import type { Order, Product, StoreSettings, User, Voucher } from "@/lib/types";
type Overview = { products: Product[]; orders: Order[]; customers: User[]; vouchers: Voucher[]; settings: StoreSettings };
const tabs = [["overview","Overview","نظرة عامة",LayoutDashboard],["products","Products","المنتجات",Package],["orders","Orders","الطلبات",ClipboardList],["customers","Customers","العملاء",Users],["vouchers","Vouchers","القسائم",TicketPercent],["settings","Settings","الإعدادات",Settings],["hsabate","API & Sync","API والمزامنة",Package]] as const;
const nextStatuses: Record<Order["status"],Order["status"][]> = { pending:["confirmed","cancelled"],confirmed:["processing","cancelled"],processing:["shipped","cancelled"],shipped:["delivered"],delivered:[],cancelled:[] };
export function Admin({ section, initial }: { section: string; initial: Overview }) {
  const { t, currency } = useStore();
  const [data,setData] = useState(initial);
  const [query,setQuery] = useState("");
  const [voucherOpen,setVoucherOpen] = useState(false);
  const [busy,setBusy] = useState(false);
  const refresh = async () => setData(await api<Overview>("admin/overview"));
  const mutate = async (path: string, method: string, body?: unknown) => { setBusy(true); try { await api(path,method,body); await refresh(); toast.success(t("Saved successfully", "تم الحفظ بنجاح")); return true; } catch(e) { toast.error(errorMessage(e)); return false; } finally { setBusy(false); } };
  const title = tabs.find(tab=>tab[0]===section)!;
  const orders = data.orders.filter(o=>`${o.id} ${o.name} ${o.phone} ${o.email}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-container py-10"><p className="eyebrow mb-3 text-primary">Oops Skin · {t("STORE ADMIN", "إدارة المتجر")}</p><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><h1 className="heading">{t(title[1],title[2])}</h1><Button asChild variant="outline"><Link href="/">{t("View storefront", "عرض المتجر")}</Link></Button></div><nav className="mb-8 flex gap-2 overflow-x-auto border-b pb-4">{tabs.map(([key,en,ar,Icon])=><Link key={key} href={key==="overview"?"/admin":`/admin/${key}`} className={cn("flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-sm",section===key?"bg-primary text-primary-foreground":"bg-muted hover:bg-secondary")}><Icon className="size-4" />{t(en,ar)}</Link>)}</nav>
  {section==="hsabate" && <HsabateDashboard onSynced={refresh} />}
  {section==="overview" && <><div className="mb-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Orders","الطلبات",data.orders.length],["Sales (excluding cancelled)","المبيعات (دون الملغي)",currency(data.orders.filter(o=>o.status!=="cancelled").reduce((s,o)=>s+o.total,0))],["Active products","المنتجات النشطة",data.products.filter(p=>p.active).length],["Customers","العملاء",data.customers.length]].map(([en,ar,value])=><div key={en} className="soft-panel"><p className="mb-3 text-sm text-muted-foreground">{t(String(en),String(ar))}</p><p className="text-3xl font-semibold text-primary">{value}</p></div>)}</div><h2 className="mb-5 text-xl font-semibold">{t("Recent orders", "أحدث الطلبات")}</h2></>}
  {["products","orders","customers"].includes(section) && <div className="mb-6 flex gap-3"><Input className="max-w-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Search…", "بحث…")} aria-label={t("Search records", "البحث في السجلات")} />{section==="products" && <Button asChild><Link href="/admin/hsabate">{t("Sync products", "مزامنة المنتجات")}</Link></Button>}</div>}
  {section==="products" && <><p className="mb-5 text-sm leading-7 text-muted-foreground">{t("Products are managed in Hsabate. Edit product details there, then use API & Sync to refresh the store.", "تُدار المنتجات في حسابات. عدّلي البيانات هناك ثم استخدمي المزامنة لتحديث المتجر.")}</p><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-160 text-start text-sm"><thead className="bg-muted"><tr>{[t("Product","المنتج"),t("Category","الفئة"),t("Price","السعر"),t("Stock","المخزون"),t("Status","الحالة"),t("Source","المصدر")].map(h=><th className="p-4 text-start font-medium" key={h}>{h}</th>)}</tr></thead><tbody>{data.products.filter(p=>`${p.name} ${p.nameAr}`.toLowerCase().includes(query.toLowerCase())).map(p=><tr className="border-t" key={p.id}><td className="p-4 font-medium">{t(p.name,p.nameAr)}</td><td className="p-4 text-muted-foreground">{p.category}</td><td className="p-4">{currency(p.price)}</td><td className="p-4">{p.stock}</td><td className="p-4">{p.active?t("Active","نشط"):t("Archived","مؤرشف")}</td><td className="p-4"><span className="text-xs text-muted-foreground">{p.externalSource === "hsabate" ? "Hsabate" : t("Local (archived after sync)", "محلي (يُؤرشف بعد المزامنة)")}</span></td></tr>)}</tbody></table></div></>}
  {["overview","orders"].includes(section) && <div className="space-y-4">{(section==="overview"?orders.slice(0,5):orders).map(o=><div key={o.id} className="soft-panel"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-sm">{o.id}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(o.createdAt).toLocaleString("en-GB")}</p></div><Status status={o.status} /><p className="font-semibold text-primary">{currency(o.total)}</p></div><details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm">{o.name} · {o.phone} · {t("Order details", "تفاصيل الطلب")}</summary><div className="mt-4 grid gap-5 text-sm md:grid-cols-2"><div className="space-y-2"><p>{o.email}</p><p>{o.city} · {o.address}</p><p>{o.notes}</p><p>{o.userId?t("Registered customer","عميل مسجل"):t("Guest checkout","شراء بدون حساب")}</p></div><div className="space-y-2">{o.items.map(i=><p key={i.productId}>{i.name} × {i.quantity} · {currency(i.price*i.quantity)}</p>)}<p>{t("Delivery","التوصيل")}: {currency(o.shipping)}</p><p>{t("Discount","الخصم")}: {currency(o.discount)}</p></div></div></details>{nextStatuses[o.status].length>0 && <div className="mt-4 flex flex-wrap gap-2">{nextStatuses[o.status].map(status=><Button key={status} size="sm" variant={status==="cancelled"?"outline":"default"} disabled={busy} onClick={()=>mutate(`admin/orders/${o.id}`,"PATCH",{status})}>{t(({confirmed:"Confirm",processing:"Prepare",shipped:"Mark shipped",delivered:"Mark delivered",cancelled:"Cancel & restore stock",pending:"Pending"})[status],({confirmed:"تأكيد",processing:"تجهيز",shipped:"تم الشحن",delivered:"تم التوصيل",cancelled:"إلغاء وإعادة المخزون",pending:"قيد الانتظار"})[status])}</Button>)}</div>}</div>)}{!orders.length && <p className="soft-panel text-sm text-muted-foreground">{t("No orders yet.","لا توجد طلبات بعد.")}</p>}</div>}
  {section==="customers" && <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-140 text-sm"><thead className="bg-muted"><tr>{[t("Name","الاسم"),t("Email","البريد الإلكتروني"),t("Phone","الهاتف"),t("Orders","الطلبات")].map(h=><th key={h} className="p-4 text-start">{h}</th>)}</tr></thead><tbody>{data.customers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase())).map(c=><tr key={c.id} className="border-t"><td className="p-4">{c.name}</td><td className="p-4">{c.email}</td><td className="p-4">{c.phone||"—"}</td><td className="p-4">{data.orders.filter(o=>o.userId===c.id).length}</td></tr>)}</tbody></table></div>}
  {section==="vouchers" && <><Button className="mb-6" onClick={()=>setVoucherOpen(true)}><Plus className="size-4" />{t("Create voucher","إنشاء قسيمة")}</Button><div className="grid gap-4 md:grid-cols-2">{data.vouchers.map(v=><div key={v.code} className="soft-panel"><div className="flex items-center justify-between"><h2 className="font-mono text-lg">{v.code}</h2><span className="text-primary">{v.percent}%</span></div><p className="my-4 text-sm text-muted-foreground">{t("Minimum","الحد الأدنى")}: {currency(v.minimum)} · {v.used}/{v.maxUses} {t("used","مستخدمة")}</p><Button variant="outline" disabled={busy||!v.active} onClick={()=>mutate(`admin/vouchers/${encodeURIComponent(v.code)}`,"DELETE")}>{v.active?t("Disable","تعطيل"):t("Disabled","معطلة")}</Button></div>)}</div>{!data.vouchers.length && <p className="text-sm text-muted-foreground">{t("No vouchers have been created.","لم يتم إنشاء قسائم بعد.")}</p>}</>}
  {section==="settings" && <form className="soft-panel max-w-xl space-y-6" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget); await mutate("admin/settings","PATCH",{shippingFee:Number(f.get("shippingFee")),freeShippingThreshold:Number(f.get("freeShippingThreshold")),contactEmail:f.get("contactEmail")});}}><p className="text-sm text-muted-foreground">{t("Currency: ILS (₪). Updated delivery settings apply to new orders. Refresh the storefront to see changes.","العملة: شيكل (₪). إعدادات التوصيل تنطبق على الطلبات الجديدة. أعيدي تحميل المتجر لعرض التغييرات.")}</p>{[["shippingFee","Delivery fee (ILS)","رسوم التوصيل (شيكل)"],["freeShippingThreshold","Free delivery from (ILS)","التوصيل المجاني من (شيكل)"],["contactEmail","Contact email (optional)","بريد التواصل (اختياري)"]].map(([name,en,ar])=><div key={name} className="field"><Label htmlFor={name}>{t(en,ar)}</Label><Input id={name} name={name} type={name==="contactEmail"?"email":"number"} min={0} step="0.01" required={name!=="contactEmail"} defaultValue={data.settings[name as keyof StoreSettings]} /></div>)}<Button type="submit" disabled={busy}>{t("Save settings","حفظ الإعدادات")}</Button></form>}
  <Dialog open={voucherOpen} onOpenChange={setVoucherOpen}><DialogContent><DialogHeader><DialogTitle>{t("Create voucher","إنشاء قسيمة")}</DialogTitle><DialogDescription>{t("Discounts are validated on the server at checkout.","يتم التحقق من الخصومات على السيرفر عند إتمام الطلب.")}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate("admin/vouchers","POST",{code:f.get("code"),percent:Number(f.get("percent")),minimum:Number(f.get("minimum")),maxUses:Number(f.get("maxUses")),active:true,expiresAt:f.get("expiresAt")?new Date(String(f.get("expiresAt"))).toISOString():null}))setVoucherOpen(false);}}>{[["code","Code","الرمز","text",""],["percent","Discount %","الخصم %","number","10"],["minimum","Minimum order (ILS)","الحد الأدنى (شيكل)","number","0"],["maxUses","Maximum uses","الحد الأقصى للاستخدام","number","100"],["expiresAt","Expires (optional)","الانتهاء (اختياري)","datetime-local",""]].map(([name,en,ar,type,value])=><div key={name} className="field"><Label htmlFor={`voucher-${name}`}>{t(en,ar)}</Label><Input id={`voucher-${name}`} name={name} type={type} defaultValue={value} required={name!=="expiresAt"} min={name==="minimum"?0:1} max={name==="percent"?100:undefined} /></div>)}<Button type="submit" disabled={busy}>{t("Create","إنشاء")}</Button></form></DialogContent></Dialog>
  </div>;
}
